blueprint:
  name: Grow Lights – Solar Noon Cycle
  description: >
    Automatically controls grow lights based on a grow start date.
    Veg weeks 1–4 run 18/6, Flower week 5+ runs 12/12.
    Lights are centered on solar noon with safe fallback to clock noon.
    This automation requires helper input_datetime.grow_start_date.
    Set the date you started your grow. Grow is based on a 12 week cycle.
    Select the light switch you wish to control.
  domain: automation

  input:
    grow_start_date:
      name: Grow Start Date
      selector:
        entity:
          domain: input_datetime

    grow_light_switch:
      name: Grow Light Switch
      selector:
        entity:
          domain: switch

mode: single

trigger:
  - platform: time_pattern
    minutes: "/1"
  - platform: homeassistant
    event: start

variables:
  start_date: !input grow_start_date
  light_switch: !input grow_light_switch

  now_ts: "{{ now().timestamp() }}"

  prev_noon: "{{ state_attr('sun.sun','previous_noon') }}"
  next_noon: "{{ state_attr('sun.sun','next_noon') }}"

  noon_ts: >
    {% if prev_noon is not none and next_noon is not none %}
      {{ as_timestamp(prev_noon if now_ts < as_timestamp(next_noon) else next_noon) }}
    {% else %}
      {{ as_timestamp(today_at('12:00')) }}
    {% endif %}

  grow_days: >
    {% if states(start_date) not in ['unknown','unavailable',''] %}
      {{ (now().date()
          - strptime(states(start_date).split(' ')[0], '%Y-%m-%d').date()).days }}
    {% else %}
      -1
    {% endif %}

  grow_week: "{{ (grow_days // 7) + 1 if grow_days >= 0 else 0 }}"

  light_hours: "{{ 18 if grow_week < 5 else 12 }}"
  half_window: "{{ (light_hours / 2) * 3600 }}"

  lights_on_ts: "{{ noon_ts - half_window }}"
  lights_off_ts: "{{ noon_ts + half_window }}"

action:
  - choose:
      # Turn lights ON
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts >= lights_on_ts and now_ts < lights_off_ts }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input grow_light_switch

      # Turn lights OFF
      - conditions:
          - condition: template
            value_template: >
              {{ now_ts < lights_on_ts or now_ts >= lights_off_ts }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input grow_light_switch

